For testing on linux
Add "-u" command for permissions of container.

Make port spec for login only used when login.

Add init.

diff --git a/alpha b/alpha
--- a/alpha
+++ b/alpha
@@ -132,10 +132,6 @@ if [ ! -z "$DISPLAY" ]; then
     fi
 fi
 
-if [ "$(uname)" = "Darwin" ]; then
-    NET=" -p 9999:9999 "
-fi
-
 if [ ! -z "$ALPHA_API_HOST" ]; then
     ENV_SETTINGS="$ENV_SETTINGS -e ALPHA_API_HOST=$ALPHA_API_HOST "
 fi
@@ -149,10 +145,34 @@ MOUNTS="$DEV_MOUNTS $X_MOUNTS -v ${PWD}:/home/carla/user-agent -v $CONFIG:/home/
 IMAGE=${IMAGE:-alphadrive/cli:0.5.7}
 
 if [ "$1" = "login" ]; then
+    if [ "$(uname)" = "Darwin" ]; then
+        NET=" -p 9999:9999 "
+    fi
+
     if [ -z "$BROWSER_LAUNCH" ]; then
         browser_warning_message authentication
     else
         start_url_open $BROWSER_LAUNCH login &
+    fi
+elif [ "$1" = "init" ]; then
+    TEMPLATE=$2
+    if [ ! -z "$TEMPLATE" ]; then
+        if [ -d "$TEMPLATE" ]; then
+            echo "A folder named $TEMPLATE already exists in this directory. Exiting..." >&2
+            exit
+        fi
+        mkdir $TEMPLATE &&
+            curl -s --location -o - https://github.com/Alpha-Drive/$TEMPLATE/archive/master.tar.gz |
+                (cd $TEMPLATE && tar -xzf - --strip 1) &&
+            echo "A sample project has been created in the folder named $TEMPLATE."
+        exit
+    else
+        echo "Template argument missing." >&2
+        echo "Usage: alpha init <TEMPLATE> where template is one of:" >&2
+        echo
+        echo "  alphadrive-samples, scenario_runner " >&2
+        echo
+        exit
     fi
 #elif [ "$1" = "drive" ]; then
     # if [ -z "$BROWSER_LAUNCH" ]; then
@@ -162,6 +182,10 @@ if [ "$1" = "login" ]; then
     # fi
 fi
 
-DOCKER_CMD="docker run $NET  --cidfile $CID_FILE --name $DOCKER_NAME --rm --init $ENV_SETTINGS "
+if [ ! -z "$SUDO_PREFIX" ]; then
+    RUN_AS_USER="-u $USER"
+fi
+
+DOCKER_CMD="docker run $NET $RUN_AS_USER --cidfile $CID_FILE --name $DOCKER_NAME --rm --init $ENV_SETTINGS "
 
 $SUDO_PREFIX $DOCKER_CMD -it $MOUNTS $ENTRYPOINT $IMAGE $@
